react routing
denis0372/otus-react pull request #6
Opened 2020-12-29 12:52 UTC by denis0372

2020-12-29 19:09 UTC, vvscode commented on jest.config.js
> +  moduleDirectories: ["node_modules", "src"],
уверен, что эта строчка нужна?

2020-12-29 19:10 UTC, vvscode commented on src/utils/authorizedOnlyHOC.tsx
> +export const authorizedOnlyHoc = <Props extends object>(
хорошо бы самому написать этот компонент и тесты к нему

2020-12-29 19:13 UTC, vvscode requested changes
Давай добавим тесты для UserScreen

2020-12-29 19:13 UTC, vvscode commented on src/utils/authorizedOnlyHOC.test.tsx
> +      `"<div>Redirect: {\\"to\\":\\"/\\"}</div>"`
в итоге я что проверяю? свой код? =)

2020-12-29 19:13 UTC, vvscode commented on src/screens/UserScreen.tsx
> +        <button onClick={this.logout}>Logout</button>
где тесты для этого кода?

2021-01-11 12:46 UTC, denis0372 commented on jest.config.js
> +  moduleDirectories: ["node_modules", "src"],
не уверен )) когда боролся с запуском тестов, добавил видимо с остальным... убрал - все работает без нее )

2021-01-11 12:47 UTC, denis0372 commented on src/screens/UserScreen.tsx
> +        <button onClick={this.logout}>Logout</button>
Да, добавил тест

2021-01-11 12:52 UTC, denis0372 commented on src/utils/authorizedOnlyHOC.tsx
> +export const authorizedOnlyHoc = <Props extends object>(
Согласен, но пока не осилил, очень уж все дается пока с болью

2021-01-15 05:36 UTC, merged